simulate 0 0 0 0
print_state

simulate 0 0 0 1
print_state

simulate 0 0 1 0
print_state

simulate 0 0 1 1
print_state

simulate 0 1 0 0
print_state

simulate 0 1 0 1
print_state

simulate 0 1 1 0
print_state

simulate 0 1 1 1
print_state

simulate 1 0 0 0
print_state

simulate 1 0 0 1
print_state

simulate 1 0 1 0
print_state

simulate 1 0 1 1
print_state

simulate 1 1 0 0
print_state

simulate 1 1 0 1
print_state

simulate 1 1 1 0
print_state

simulate 1 1 1 1
print_state